# Generated by Django 4.2.2 on 2023-06-06 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=50)),
                ('categoria', models.CharField(blank=True, max_length=50)),
                ('tipo', models.CharField(blank=True, max_length=50)),
                ('imagen', models.ImageField(upload_to='imagen_pokemon/')),
                ('valor', models.IntegerField(null=True)),
            ],
        ),
    ]
